/**
 * C-side-simulating encoders for the formats that only travel C→JS
 * (4. MESSAGE BATCH, 5. EVENT FRAME).
 *
 * Written to TRACK each field of `native/include/bunrdkafka.h` so round-trip
 * tests genuinely verify the layout instead of testing the decoder against
 * itself. Binary fixtures generated by a C test harness (docs §11) will
 * replace/augment this in M2.
 */

import { toArrayBuffer, type Pointer } from "bun:ffi";

import { BufReader, BufWriter } from "../../../packages/bun-rdkafka/src/core/binary.ts";
import { encodeTpl, type TopicPartitionInput } from "../../../packages/bun-rdkafka/src/core/batch-decoder.ts";

/* ----------------------------------------------------- 3. PRODUCE BATCH */

export interface DecodedProduceRecord {
  topic: string;
  partition: number;
  timestampMs: bigint;
  opaqueId: bigint;
  key: Uint8Array | null;
  value: Uint8Array | null;
  headers: { key: string; value: Uint8Array | null }[];
}

/**
 * An independent PRODUCE BATCH decoder — reads per the header spec, playing
 * the C-side `brk_produce_batch` so round-trips do not self-verify against the
 * encoder.
 */
/**
 * Reads one format-3 `(u64 ptr, i32 len)` field exactly like C: len -1 →
 * null, len 0 → empty, len > 0 → deref the pointer into JS memory via
 * `toArrayBuffer` (copied out so asserts stay safe after the caller drops the
 * buffer).
 */
function readPtrField(r: BufReader): Uint8Array | null {
  const p = r.u64();
  const len = r.i32();
  if (len === -1) return null;
  if (len === 0) return new Uint8Array(0);
  if (p === 0n) throw new Error("format 3: len > 0 but ptr == 0");
  return new Uint8Array(toArrayBuffer(Number(p) as Pointer, 0, len)).slice();
}

export function decodeProduceBatch(buf: Uint8Array): DecodedProduceRecord[] {
  const r = new BufReader(buf);
  const count = r.u32();
  const out: DecodedProduceRecord[] = [];
  for (let i = 0; i < count; i++) {
    const topic = r.stringU16();
    const partition = r.i32();
    const timestampMs = r.i64();
    const opaqueId = r.u64();
    const key = readPtrField(r);
    const value = readPtrField(r);
    const headerCount = r.u16();
    const headers: { key: string; value: Uint8Array | null }[] = [];
    for (let h = 0; h < headerCount; h++) {
      headers.push({ key: r.stringU16(), value: r.bytesI32() });
    }
    out.push({ topic, partition, timestampMs, opaqueId, key, value, headers });
  }
  if (!r.eof) throw new Error(`PRODUCE BATCH has ${r.remaining} leftover bytes`);
  return out;
}

/* ------------------------------------------------------ 4. MESSAGE BATCH */

export interface RawMessage {
  topicId: number;
  partition: number;
  offset: number | bigint;
  timestampMs: number | bigint;
  timestampType: number;
  err: number;
  key: Uint8Array | string | null;
  value: Uint8Array | string | null;
  headers?: { key: string; value: Uint8Array | string | null }[];
  leaderEpoch?: number;
}

/** `count` back-to-back records, NO count prefix (count is the return value). */
export function encodeMessageBatch(messages: readonly RawMessage[]): Uint8Array {
  const w = new BufWriter(256);
  for (const m of messages) {
    w.i32(m.topicId);
    w.i32(m.partition);
    w.i64(m.offset);
    w.i64(m.timestampMs);
    w.u8(m.timestampType);
    w.i16(m.err);
    w.bytesI32(m.key);
    w.bytesI32(m.value);
    const headers = m.headers ?? [];
    w.u16(headers.length);
    for (const h of headers) {
      w.stringU16(h.key);
      w.bytesI32(h.value);
    }
    w.i32(m.leaderEpoch ?? -1);
  }
  return w.toBytes();
}

/* -------------------------------------------------------- 5. EVENT FRAME */

/** Back-to-back `{ u8 event_type, u32 payload_len, bytes payload }`. */
export function encodeEventFrames(
  frames: readonly { type: number; payload: Uint8Array }[],
): Uint8Array {
  const w = new BufWriter(256);
  for (const f of frames) {
    w.u8(f.type);
    w.u32(f.payload.length);
    w.bytes(f.payload);
  }
  return w.toBytes();
}

function payload(build: (w: BufWriter) => void): Uint8Array {
  const w = new BufWriter(128);
  build(w);
  return w.toBytes();
}

export interface RawDeliveryReport {
  opaqueId: bigint;
  err: number;
  partition: number;
  offset: number | bigint;
  timestampMs: number | bigint;
}

/** `u32 n; n × { u64 opaque_id, i16 err, i32 partition, i64 offset, i64 timestamp_ms }` */
export function drPayload(reports: readonly RawDeliveryReport[]): Uint8Array {
  return payload((w) => {
    w.u32(reports.length);
    for (const r of reports) {
      w.u64(r.opaqueId);
      w.i16(r.err);
      w.i32(r.partition);
      w.i64(r.offset);
      w.i64(r.timestampMs);
    }
  });
}

/** `i32 kafka_err, u8 is_fatal, u16 reason_len, bytes reason` */
export function errorPayload(kafkaErr: number, isFatal: boolean, reason: string): Uint8Array {
  return payload((w) => {
    w.i32(kafkaErr);
    w.u8(isFatal ? 1 : 0);
    w.stringU16(reason);
  });
}

/** `i32 level, u16 fac_len, bytes fac, u32 msg_len, bytes msg` */
export function logPayload(level: number, fac: string, message: string): Uint8Array {
  return payload((w) => {
    w.i32(level);
    w.stringU16(fac);
    w.stringU32(message);
  });
}

/** `u32 json_len, bytes json` */
export function statsPayload(json: string): Uint8Array {
  return payload((w) => w.stringU32(json));
}

/** `i32 kafka_err, u8 protocol, u8 assignment_lost, tpl` */
export function rebalancePayload(
  kafkaErr: number,
  protocol: number,
  partitions: readonly TopicPartitionInput[],
  assignmentLost = false,
): Uint8Array {
  return payload((w) => {
    w.i32(kafkaErr);
    w.u8(protocol);
    w.u8(assignmentLost ? 1 : 0);
    encodeTpl(partitions, w);
  });
}

/** `i32 kafka_err, tpl` */
export function offsetCommitPayload(
  kafkaErr: number,
  partitions: readonly TopicPartitionInput[],
): Uint8Array {
  return payload((w) => {
    w.i32(kafkaErr);
    encodeTpl(partitions, w);
  });
}

/** `i32 broker_id, i32 throttle_ms, u16 name_len, bytes broker_name` */
export function throttlePayload(
  brokerId: number,
  throttleMs: number,
  brokerName: string,
): Uint8Array {
  return payload((w) => {
    w.i32(brokerId);
    w.i32(throttleMs);
    w.stringU16(brokerName);
  });
}

/** `u16 cfg_len, bytes oauthbearer_config` */
export function oauthRefreshPayload(config: string): Uint8Array {
  return payload((w) => w.stringU16(config));
}

/** `u64 correlation_id, i32 kafka_err, u32 json_len, bytes json` */
export function adminResultPayload(
  correlationId: bigint,
  kafkaErr: number,
  json: string,
): Uint8Array {
  return payload((w) => {
    w.u64(correlationId);
    w.i32(kafkaErr);
    w.stringU32(json);
  });
}
