/**
 * core/errors.ts — `LibrdKafkaError` + `CODES.ERRORS` (design §5.5).
 *
 * The error-code table is a copy of `rd_kafka_resp_err_t` from
 * `librdkafka/src/rdkafka.h` at tag **v2.15.0** (matching `librdkafka.version`),
 * with names stripped of the `RD_KAFKA_RESP_` prefix exactly like
 * confluent-kafka-javascript / node-rdkafka's `CODES.ERRORS`.
 *
 * TODO(M2): replace this hand-copied table with `scripts/gen-error-codes.ts`
 * running in CI, reading the pinned version's `rdkafka.h` and overwriting this
 * file — for now the table must be regenerated BY HAND whenever
 * `librdkafka.version` changes.
 *
 * Descriptions in `ERROR_DESCRIPTIONS` come from the header's doc comments.
 * They are NOT `rd_kafka_err2str()` strings; when a handle is available, the
 * precise message comes from `brk_last_error_string()` and is passed to the
 * constructor.
 */

import {
  BRK_ERR_NAMES,
  isKafkaErr,
  isShimErr,
  kafkaErrOf,
} from "../ffi/types.ts";

/* ========================================================================== */
/* Error-code table (generated from rdkafka.h v2.15.0)                         */
/* ========================================================================== */

export const ERROR_CODES = {
  /** Begin internal error codes */
  ERR__BEGIN: -200,
  /** Received message is incorrect */
  ERR__BAD_MSG: -199,
  /** Bad/unknown compression */
  ERR__BAD_COMPRESSION: -198,
  /** Broker is going away, together with client instance */
  ERR__DESTROY: -197,
  /** Generic failure */
  ERR__FAIL: -196,
  /** Broker transport failure */
  ERR__TRANSPORT: -195,
  /** Critical system resource */
  ERR__CRIT_SYS_RESOURCE: -194,
  /** Failed to resolve broker */
  ERR__RESOLVE: -193,
  /** Produced message timed out */
  ERR__MSG_TIMED_OUT: -192,
  /** Reached the end of the topic+partition queue on the broker. Not really an error. This event is disabled by default, see the `enable.partition.eof` configuration property. */
  ERR__PARTITION_EOF: -191,
  /** Permanent: Partition does not exist in cluster. */
  ERR__UNKNOWN_PARTITION: -190,
  /** File or filesystem error */
  ERR__FS: -189,
  /** Permanent: Topic does not exist in cluster. */
  ERR__UNKNOWN_TOPIC: -188,
  /** All broker connections are down. */
  ERR__ALL_BROKERS_DOWN: -187,
  /** Invalid argument, or invalid configuration */
  ERR__INVALID_ARG: -186,
  /** Operation timed out */
  ERR__TIMED_OUT: -185,
  /** Queue is full */
  ERR__QUEUE_FULL: -184,
  /** ISR count < required.acks */
  ERR__ISR_INSUFF: -183,
  /** Broker node update */
  ERR__NODE_UPDATE: -182,
  /** SSL error */
  ERR__SSL: -181,
  /** Waiting for coordinator to become available. */
  ERR__WAIT_COORD: -180,
  /** Unknown client group */
  ERR__UNKNOWN_GROUP: -179,
  /** Operation in progress */
  ERR__IN_PROGRESS: -178,
  /** Previous operation in progress, wait for it to finish. */
  ERR__PREV_IN_PROGRESS: -177,
  /** This operation would interfere with an existing subscription */
  ERR__EXISTING_SUBSCRIPTION: -176,
  /** Assigned partitions (rebalance_cb) */
  ERR__ASSIGN_PARTITIONS: -175,
  /** Revoked partitions (rebalance_cb) */
  ERR__REVOKE_PARTITIONS: -174,
  /** Conflicting use */
  ERR__CONFLICT: -173,
  /** Wrong state */
  ERR__STATE: -172,
  /** Unknown protocol */
  ERR__UNKNOWN_PROTOCOL: -171,
  /** Not implemented */
  ERR__NOT_IMPLEMENTED: -170,
  /** Authentication failure */
  ERR__AUTHENTICATION: -169,
  /** No stored offset */
  ERR__NO_OFFSET: -168,
  /** Outdated */
  ERR__OUTDATED: -167,
  /** Timed out in queue */
  ERR__TIMED_OUT_QUEUE: -166,
  /** Feature not supported by broker */
  ERR__UNSUPPORTED_FEATURE: -165,
  /** Awaiting cache update */
  ERR__WAIT_CACHE: -164,
  /** Operation interrupted (e.g., due to yield)) */
  ERR__INTR: -163,
  /** Key serialization error */
  ERR__KEY_SERIALIZATION: -162,
  /** Value serialization error */
  ERR__VALUE_SERIALIZATION: -161,
  /** Key deserialization error */
  ERR__KEY_DESERIALIZATION: -160,
  /** Value deserialization error */
  ERR__VALUE_DESERIALIZATION: -159,
  /** Partial response */
  ERR__PARTIAL: -158,
  /** Modification attempted on read-only object */
  ERR__READ_ONLY: -157,
  /** No such entry / item not found */
  ERR__NOENT: -156,
  /** Read underflow */
  ERR__UNDERFLOW: -155,
  /** Invalid type */
  ERR__INVALID_TYPE: -154,
  /** Retry operation */
  ERR__RETRY: -153,
  /** Purged in queue */
  ERR__PURGE_QUEUE: -152,
  /** Purged in flight */
  ERR__PURGE_INFLIGHT: -151,
  /** Fatal error: see rd_kafka_fatal_error() */
  ERR__FATAL: -150,
  /** Inconsistent state */
  ERR__INCONSISTENT: -149,
  /** Gap-less ordering would not be guaranteed if proceeding */
  ERR__GAPLESS_GUARANTEE: -148,
  /** Maximum poll interval exceeded */
  ERR__MAX_POLL_EXCEEDED: -147,
  /** Unknown broker */
  ERR__UNKNOWN_BROKER: -146,
  /** Functionality not configured */
  ERR__NOT_CONFIGURED: -145,
  /** Instance has been fenced */
  ERR__FENCED: -144,
  /** Application generated error */
  ERR__APPLICATION: -143,
  /** Assignment lost */
  ERR__ASSIGNMENT_LOST: -142,
  /** No operation performed */
  ERR__NOOP: -141,
  /** No offset to automatically reset to */
  ERR__AUTO_OFFSET_RESET: -140,
  /** Partition log truncation detected */
  ERR__LOG_TRUNCATION: -139,
  /** A different record in the batch was invalid and this message failed persisting. */
  ERR__INVALID_DIFFERENT_RECORD: -138,
  /** Broker is going away but client isn't terminating */
  ERR__DESTROY_BROKER: -137,
  /** End internal error codes */
  ERR__END: -100,
  /** Unknown broker error */
  ERR_UNKNOWN: -1,
  /** Success */
  ERR_NO_ERROR: 0,
  /** Offset out of range */
  ERR_OFFSET_OUT_OF_RANGE: 1,
  /** Invalid message */
  ERR_INVALID_MSG: 2,
  /** Unknown topic or partition */
  ERR_UNKNOWN_TOPIC_OR_PART: 3,
  /** Invalid message size */
  ERR_INVALID_MSG_SIZE: 4,
  /** Leader not available */
  ERR_LEADER_NOT_AVAILABLE: 5,
  /** Not leader for partition */
  ERR_NOT_LEADER_FOR_PARTITION: 6,
  /** Request timed out */
  ERR_REQUEST_TIMED_OUT: 7,
  /** Broker not available */
  ERR_BROKER_NOT_AVAILABLE: 8,
  /** Replica not available */
  ERR_REPLICA_NOT_AVAILABLE: 9,
  /** Message size too large */
  ERR_MSG_SIZE_TOO_LARGE: 10,
  /** StaleControllerEpochCode */
  ERR_STALE_CTRL_EPOCH: 11,
  /** Offset metadata string too large */
  ERR_OFFSET_METADATA_TOO_LARGE: 12,
  /** Broker disconnected before response received */
  ERR_NETWORK_EXCEPTION: 13,
  /** Coordinator load in progress */
  ERR_COORDINATOR_LOAD_IN_PROGRESS: 14,
  /** Group coordinator load in progress (legacy name of `ERR_COORDINATOR_LOAD_IN_PROGRESS`) */
  ERR_GROUP_LOAD_IN_PROGRESS: 14,
  /** Coordinator not available */
  ERR_COORDINATOR_NOT_AVAILABLE: 15,
  /** Group coordinator not available (legacy name of `ERR_COORDINATOR_NOT_AVAILABLE`) */
  ERR_GROUP_COORDINATOR_NOT_AVAILABLE: 15,
  /** Not coordinator */
  ERR_NOT_COORDINATOR: 16,
  /** Not coordinator for group (legacy name of `ERR_NOT_COORDINATOR`) */
  ERR_NOT_COORDINATOR_FOR_GROUP: 16,
  /** Invalid topic */
  ERR_TOPIC_EXCEPTION: 17,
  /** Message batch larger than configured server segment size */
  ERR_RECORD_LIST_TOO_LARGE: 18,
  /** Not enough in-sync replicas */
  ERR_NOT_ENOUGH_REPLICAS: 19,
  /** Message(s) written to insufficient number of in-sync replicas */
  ERR_NOT_ENOUGH_REPLICAS_AFTER_APPEND: 20,
  /** Invalid required acks value */
  ERR_INVALID_REQUIRED_ACKS: 21,
  /** Specified group generation id is not valid */
  ERR_ILLEGAL_GENERATION: 22,
  /** Inconsistent group protocol */
  ERR_INCONSISTENT_GROUP_PROTOCOL: 23,
  /** Invalid group.id */
  ERR_INVALID_GROUP_ID: 24,
  /** Unknown member */
  ERR_UNKNOWN_MEMBER_ID: 25,
  /** Invalid session timeout */
  ERR_INVALID_SESSION_TIMEOUT: 26,
  /** Group rebalance in progress */
  ERR_REBALANCE_IN_PROGRESS: 27,
  /** Commit offset data size is not valid */
  ERR_INVALID_COMMIT_OFFSET_SIZE: 28,
  /** Topic authorization failed */
  ERR_TOPIC_AUTHORIZATION_FAILED: 29,
  /** Group authorization failed */
  ERR_GROUP_AUTHORIZATION_FAILED: 30,
  /** Cluster authorization failed */
  ERR_CLUSTER_AUTHORIZATION_FAILED: 31,
  /** Invalid timestamp */
  ERR_INVALID_TIMESTAMP: 32,
  /** Unsupported SASL mechanism */
  ERR_UNSUPPORTED_SASL_MECHANISM: 33,
  /** Illegal SASL state */
  ERR_ILLEGAL_SASL_STATE: 34,
  /** Unuspported version */
  ERR_UNSUPPORTED_VERSION: 35,
  /** Topic already exists */
  ERR_TOPIC_ALREADY_EXISTS: 36,
  /** Invalid number of partitions */
  ERR_INVALID_PARTITIONS: 37,
  /** Invalid replication factor */
  ERR_INVALID_REPLICATION_FACTOR: 38,
  /** Invalid replica assignment */
  ERR_INVALID_REPLICA_ASSIGNMENT: 39,
  /** Invalid config */
  ERR_INVALID_CONFIG: 40,
  /** Not controller for cluster */
  ERR_NOT_CONTROLLER: 41,
  /** Invalid request */
  ERR_INVALID_REQUEST: 42,
  /** Message format on broker does not support request */
  ERR_UNSUPPORTED_FOR_MESSAGE_FORMAT: 43,
  /** Policy violation */
  ERR_POLICY_VIOLATION: 44,
  /** Broker received an out of order sequence number */
  ERR_OUT_OF_ORDER_SEQUENCE_NUMBER: 45,
  /** Broker received a duplicate sequence number */
  ERR_DUPLICATE_SEQUENCE_NUMBER: 46,
  /** Producer attempted an operation with an old epoch */
  ERR_INVALID_PRODUCER_EPOCH: 47,
  /** Producer attempted a transactional operation in an invalid state */
  ERR_INVALID_TXN_STATE: 48,
  /** Producer attempted to use a producer id which is not currently assigned to its transactional id */
  ERR_INVALID_PRODUCER_ID_MAPPING: 49,
  /** Transaction timeout is larger than the maximum value allowed by the broker's max.transaction.timeout.ms */
  ERR_INVALID_TRANSACTION_TIMEOUT: 50,
  /** Producer attempted to update a transaction while another concurrent operation on the same transaction was ongoing */
  ERR_CONCURRENT_TRANSACTIONS: 51,
  /** Indicates that the transaction coordinator sending a WriteTxnMarker is no longer the current coordinator for a given producer */
  ERR_TRANSACTION_COORDINATOR_FENCED: 52,
  /** Transactional Id authorization failed */
  ERR_TRANSACTIONAL_ID_AUTHORIZATION_FAILED: 53,
  /** Security features are disabled */
  ERR_SECURITY_DISABLED: 54,
  /** Operation not attempted */
  ERR_OPERATION_NOT_ATTEMPTED: 55,
  /** Disk error when trying to access log file on the disk */
  ERR_KAFKA_STORAGE_ERROR: 56,
  /** The user-specified log directory is not found in the broker config */
  ERR_LOG_DIR_NOT_FOUND: 57,
  /** SASL Authentication failed */
  ERR_SASL_AUTHENTICATION_FAILED: 58,
  /** Unknown Producer Id */
  ERR_UNKNOWN_PRODUCER_ID: 59,
  /** Partition reassignment is in progress */
  ERR_REASSIGNMENT_IN_PROGRESS: 60,
  /** Delegation Token feature is not enabled */
  ERR_DELEGATION_TOKEN_AUTH_DISABLED: 61,
  /** Delegation Token is not found on server */
  ERR_DELEGATION_TOKEN_NOT_FOUND: 62,
  /** Specified Principal is not valid Owner/Renewer */
  ERR_DELEGATION_TOKEN_OWNER_MISMATCH: 63,
  /** Delegation Token requests are not allowed on this connection */
  ERR_DELEGATION_TOKEN_REQUEST_NOT_ALLOWED: 64,
  /** Delegation Token authorization failed */
  ERR_DELEGATION_TOKEN_AUTHORIZATION_FAILED: 65,
  /** Delegation Token is expired */
  ERR_DELEGATION_TOKEN_EXPIRED: 66,
  /** Supplied principalType is not supported */
  ERR_INVALID_PRINCIPAL_TYPE: 67,
  /** The group is not empty */
  ERR_NON_EMPTY_GROUP: 68,
  /** The group id does not exist */
  ERR_GROUP_ID_NOT_FOUND: 69,
  /** The fetch session ID was not found */
  ERR_FETCH_SESSION_ID_NOT_FOUND: 70,
  /** The fetch session epoch is invalid */
  ERR_INVALID_FETCH_SESSION_EPOCH: 71,
  /** No matching listener */
  ERR_LISTENER_NOT_FOUND: 72,
  /** Topic deletion is disabled */
  ERR_TOPIC_DELETION_DISABLED: 73,
  /** Leader epoch is older than broker epoch */
  ERR_FENCED_LEADER_EPOCH: 74,
  /** Leader epoch is newer than broker epoch */
  ERR_UNKNOWN_LEADER_EPOCH: 75,
  /** Unsupported compression type */
  ERR_UNSUPPORTED_COMPRESSION_TYPE: 76,
  /** Broker epoch has changed */
  ERR_STALE_BROKER_EPOCH: 77,
  /** Leader high watermark is not caught up */
  ERR_OFFSET_NOT_AVAILABLE: 78,
  /** Group member needs a valid member ID */
  ERR_MEMBER_ID_REQUIRED: 79,
  /** Preferred leader was not available */
  ERR_PREFERRED_LEADER_NOT_AVAILABLE: 80,
  /** Consumer group has reached maximum size */
  ERR_GROUP_MAX_SIZE_REACHED: 81,
  /** Static consumer fenced by other consumer with same group.instance.id. */
  ERR_FENCED_INSTANCE_ID: 82,
  /** Eligible partition leaders are not available */
  ERR_ELIGIBLE_LEADERS_NOT_AVAILABLE: 83,
  /** Leader election not needed for topic partition */
  ERR_ELECTION_NOT_NEEDED: 84,
  /** No partition reassignment is in progress */
  ERR_NO_REASSIGNMENT_IN_PROGRESS: 85,
  /** Deleting offsets of a topic while the consumer group is subscribed to it */
  ERR_GROUP_SUBSCRIBED_TO_TOPIC: 86,
  /** Broker failed to validate record */
  ERR_INVALID_RECORD: 87,
  /** There are unstable offsets that need to be cleared */
  ERR_UNSTABLE_OFFSET_COMMIT: 88,
  /** Throttling quota has been exceeded */
  ERR_THROTTLING_QUOTA_EXCEEDED: 89,
  /** There is a newer producer with the same transactionalId which fences the current one */
  ERR_PRODUCER_FENCED: 90,
  /** Request illegally referred to resource that does not exist */
  ERR_RESOURCE_NOT_FOUND: 91,
  /** Request illegally referred to the same resource twice */
  ERR_DUPLICATE_RESOURCE: 92,
  /** Requested credential would not meet criteria for acceptability */
  ERR_UNACCEPTABLE_CREDENTIAL: 93,
  /** Indicates that the either the sender or recipient of a voter-only request is not one of the expected voters */
  ERR_INCONSISTENT_VOTER_SET: 94,
  /** Invalid update version */
  ERR_INVALID_UPDATE_VERSION: 95,
  /** Unable to update finalized features due to server error */
  ERR_FEATURE_UPDATE_FAILED: 96,
  /** Request principal deserialization failed during forwarding */
  ERR_PRINCIPAL_DESERIALIZATION_FAILURE: 97,
  /** Unknown Topic Id */
  ERR_UNKNOWN_TOPIC_ID: 100,
  /** The log's topic ID did not match the topic ID in the request */
  ERR_INCONSISTENT_TOPIC_ID: 103,
  /** The member epoch is fenced by the group coordinator */
  ERR_FENCED_MEMBER_EPOCH: 110,
  /** The instance ID is still used by another member in the consumer group */
  ERR_UNRELEASED_INSTANCE_ID: 111,
  /** The assignor or its version range is not supported by the consumer group */
  ERR_UNSUPPORTED_ASSIGNOR: 112,
  /** The member epoch is stale */
  ERR_STALE_MEMBER_EPOCH: 113,
  /** The request was sent to an endpoint of the wrong type. */
  ERR_MISMATCHED_ENDPOINT_TYPE: 114,
  /** This endpoint type is not supported yet. */
  ERR_UNSUPPORTED_ENDPOINT_TYPE: 115,
  /** This controller ID is not known. */
  ERR_UNKNOWN_CONTROLLER_ID: 116,
  /** Client sent a push telemetry request with an invalid or outdated subscription ID. */
  ERR_UNKNOWN_SUBSCRIPTION_ID: 117,
  /** Client sent a push telemetry request larger than the maximum size the broker will accept. */
  ERR_TELEMETRY_TOO_LARGE: 118,
  /** The controller has considered the broker registration to be invalid. */
  ERR_INVALID_REGISTRATION: 119,
  /** The server encountered an error with the transaction. The client can abort the transaction to continue using this transactional ID. */
  ERR_TRANSACTION_ABORTABLE: 120,
  /** The record state is invalid. The acknowledgement of delivery could not be completed. */
  ERR_INVALID_RECORD_STATE: 121,
  /** The share session was not found. */
  ERR_SHARE_SESSION_NOT_FOUND: 122,
  /** The share session epoch is invalid. */
  ERR_INVALID_SHARE_SESSION_EPOCH: 123,
  /** The share coordinator rejected the request because the share-group state epoch did not match. */
  ERR_FENCED_STATE_EPOCH: 124,
  /** The voter key doesn't match the receiving replica's key. */
  ERR_INVALID_VOTER_KEY: 125,
  /** The voter is already part of the set of voters. */
  ERR_DUPLICATE_VOTER: 126,
  /** The voter is not part of the set of voters. */
  ERR_VOTER_NOT_FOUND: 127,
  /** The regular expression is not valid. */
  ERR_INVALID_REGULAR_EXPRESSION: 128,
  /** Client metadata is stale, client should rebootstrap to obtain new metadata. */
  ERR_REBOOTSTRAP_REQUIRED: 129,
  /** The supplied topology is invalid. */
  ERR_STREAMS_INVALID_TOPOLOGY: 130,
  /** The supplied topology epoch is invalid. */
  ERR_STREAMS_INVALID_TOPOLOGY_EPOCH: 131,
  /** The supplied topology epoch is outdated. */
  ERR_STREAMS_TOPOLOGY_FENCED: 132,
  /** The limit of share sessions has been reached. */
  ERR_SHARE_SESSION_LIMIT_REACHED: 133,
  ERR_END_ALL: 134,
} as const;

export type ErrorCodeName = keyof typeof ERROR_CODES;

/** Upstream compatibility: `Kafka.CODES.ERRORS.ERR__TIMED_OUT`. */
export const CODES = { ERRORS: ERROR_CODES } as const;

/** Short descriptions from rdkafka.h's doc comments (fallback when no handle). */
export const ERROR_DESCRIPTIONS: ReadonlyMap<number, string> = new Map<number, string>([
  [-200, "Begin internal error codes"],
  [-199, "Received message is incorrect"],
  [-198, "Bad/unknown compression"],
  [-197, "Broker is going away, together with client instance"],
  [-196, "Generic failure"],
  [-195, "Broker transport failure"],
  [-194, "Critical system resource"],
  [-193, "Failed to resolve broker"],
  [-192, "Produced message timed out"],
  [-191, "Reached the end of the topic+partition queue on the broker. Not really an error. This event is disabled by default, see the `enable.partition.eof` configuration property."],
  [-190, "Permanent: Partition does not exist in cluster."],
  [-189, "File or filesystem error"],
  [-188, "Permanent: Topic does not exist in cluster."],
  [-187, "All broker connections are down."],
  [-186, "Invalid argument, or invalid configuration"],
  [-185, "Operation timed out"],
  [-184, "Queue is full"],
  [-183, "ISR count < required.acks"],
  [-182, "Broker node update"],
  [-181, "SSL error"],
  [-180, "Waiting for coordinator to become available."],
  [-179, "Unknown client group"],
  [-178, "Operation in progress"],
  [-177, "Previous operation in progress, wait for it to finish."],
  [-176, "This operation would interfere with an existing subscription"],
  [-175, "Assigned partitions (rebalance_cb)"],
  [-174, "Revoked partitions (rebalance_cb)"],
  [-173, "Conflicting use"],
  [-172, "Wrong state"],
  [-171, "Unknown protocol"],
  [-170, "Not implemented"],
  [-169, "Authentication failure"],
  [-168, "No stored offset"],
  [-167, "Outdated"],
  [-166, "Timed out in queue"],
  [-165, "Feature not supported by broker"],
  [-164, "Awaiting cache update"],
  [-163, "Operation interrupted (e.g., due to yield))"],
  [-162, "Key serialization error"],
  [-161, "Value serialization error"],
  [-160, "Key deserialization error"],
  [-159, "Value deserialization error"],
  [-158, "Partial response"],
  [-157, "Modification attempted on read-only object"],
  [-156, "No such entry / item not found"],
  [-155, "Read underflow"],
  [-154, "Invalid type"],
  [-153, "Retry operation"],
  [-152, "Purged in queue"],
  [-151, "Purged in flight"],
  [-150, "Fatal error: see rd_kafka_fatal_error()"],
  [-149, "Inconsistent state"],
  [-148, "Gap-less ordering would not be guaranteed if proceeding"],
  [-147, "Maximum poll interval exceeded"],
  [-146, "Unknown broker"],
  [-145, "Functionality not configured"],
  [-144, "Instance has been fenced"],
  [-143, "Application generated error"],
  [-142, "Assignment lost"],
  [-141, "No operation performed"],
  [-140, "No offset to automatically reset to"],
  [-139, "Partition log truncation detected"],
  [-138, "A different record in the batch was invalid and this message failed persisting."],
  [-137, "Broker is going away but client isn't terminating"],
  [-100, "End internal error codes"],
  [-1, "Unknown broker error"],
  [0, "Success"],
  [1, "Offset out of range"],
  [2, "Invalid message"],
  [3, "Unknown topic or partition"],
  [4, "Invalid message size"],
  [5, "Leader not available"],
  [6, "Not leader for partition"],
  [7, "Request timed out"],
  [8, "Broker not available"],
  [9, "Replica not available"],
  [10, "Message size too large"],
  [11, "StaleControllerEpochCode"],
  [12, "Offset metadata string too large"],
  [13, "Broker disconnected before response received"],
  [14, "Coordinator load in progress"],
  [15, "Coordinator not available"],
  [16, "Not coordinator"],
  [17, "Invalid topic"],
  [18, "Message batch larger than configured server segment size"],
  [19, "Not enough in-sync replicas"],
  [20, "Message(s) written to insufficient number of in-sync replicas"],
  [21, "Invalid required acks value"],
  [22, "Specified group generation id is not valid"],
  [23, "Inconsistent group protocol"],
  [24, "Invalid group.id"],
  [25, "Unknown member"],
  [26, "Invalid session timeout"],
  [27, "Group rebalance in progress"],
  [28, "Commit offset data size is not valid"],
  [29, "Topic authorization failed"],
  [30, "Group authorization failed"],
  [31, "Cluster authorization failed"],
  [32, "Invalid timestamp"],
  [33, "Unsupported SASL mechanism"],
  [34, "Illegal SASL state"],
  [35, "Unuspported version"],
  [36, "Topic already exists"],
  [37, "Invalid number of partitions"],
  [38, "Invalid replication factor"],
  [39, "Invalid replica assignment"],
  [40, "Invalid config"],
  [41, "Not controller for cluster"],
  [42, "Invalid request"],
  [43, "Message format on broker does not support request"],
  [44, "Policy violation"],
  [45, "Broker received an out of order sequence number"],
  [46, "Broker received a duplicate sequence number"],
  [47, "Producer attempted an operation with an old epoch"],
  [48, "Producer attempted a transactional operation in an invalid state"],
  [49, "Producer attempted to use a producer id which is not currently assigned to its transactional id"],
  [50, "Transaction timeout is larger than the maximum value allowed by the broker's max.transaction.timeout.ms"],
  [51, "Producer attempted to update a transaction while another concurrent operation on the same transaction was ongoing"],
  [52, "Indicates that the transaction coordinator sending a WriteTxnMarker is no longer the current coordinator for a given producer"],
  [53, "Transactional Id authorization failed"],
  [54, "Security features are disabled"],
  [55, "Operation not attempted"],
  [56, "Disk error when trying to access log file on the disk"],
  [57, "The user-specified log directory is not found in the broker config"],
  [58, "SASL Authentication failed"],
  [59, "Unknown Producer Id"],
  [60, "Partition reassignment is in progress"],
  [61, "Delegation Token feature is not enabled"],
  [62, "Delegation Token is not found on server"],
  [63, "Specified Principal is not valid Owner/Renewer"],
  [64, "Delegation Token requests are not allowed on this connection"],
  [65, "Delegation Token authorization failed"],
  [66, "Delegation Token is expired"],
  [67, "Supplied principalType is not supported"],
  [68, "The group is not empty"],
  [69, "The group id does not exist"],
  [70, "The fetch session ID was not found"],
  [71, "The fetch session epoch is invalid"],
  [72, "No matching listener"],
  [73, "Topic deletion is disabled"],
  [74, "Leader epoch is older than broker epoch"],
  [75, "Leader epoch is newer than broker epoch"],
  [76, "Unsupported compression type"],
  [77, "Broker epoch has changed"],
  [78, "Leader high watermark is not caught up"],
  [79, "Group member needs a valid member ID"],
  [80, "Preferred leader was not available"],
  [81, "Consumer group has reached maximum size"],
  [82, "Static consumer fenced by other consumer with same group.instance.id."],
  [83, "Eligible partition leaders are not available"],
  [84, "Leader election not needed for topic partition"],
  [85, "No partition reassignment is in progress"],
  [86, "Deleting offsets of a topic while the consumer group is subscribed to it"],
  [87, "Broker failed to validate record"],
  [88, "There are unstable offsets that need to be cleared"],
  [89, "Throttling quota has been exceeded"],
  [90, "There is a newer producer with the same transactionalId which fences the current one"],
  [91, "Request illegally referred to resource that does not exist"],
  [92, "Request illegally referred to the same resource twice"],
  [93, "Requested credential would not meet criteria for acceptability"],
  [94, "Indicates that the either the sender or recipient of a voter-only request is not one of the expected voters"],
  [95, "Invalid update version"],
  [96, "Unable to update finalized features due to server error"],
  [97, "Request principal deserialization failed during forwarding"],
  [100, "Unknown Topic Id"],
  [103, "The log's topic ID did not match the topic ID in the request"],
  [110, "The member epoch is fenced by the group coordinator"],
  [111, "The instance ID is still used by another member in the consumer group"],
  [112, "The assignor or its version range is not supported by the consumer group"],
  [113, "The member epoch is stale"],
  [114, "The request was sent to an endpoint of the wrong type."],
  [115, "This endpoint type is not supported yet."],
  [116, "This controller ID is not known."],
  [117, "Client sent a push telemetry request with an invalid or outdated subscription ID."],
  [118, "Client sent a push telemetry request larger than the maximum size the broker will accept."],
  [119, "The controller has considered the broker registration to be invalid."],
  [120, "The server encountered an error with the transaction. The client can abort the transaction to continue using this transactional ID."],
  [121, "The record state is invalid. The acknowledgement of delivery could not be completed."],
  [122, "The share session was not found."],
  [123, "The share session epoch is invalid."],
  [124, "The share coordinator rejected the request because the share-group state epoch did not match."],
  [125, "The voter key doesn't match the receiving replica's key."],
  [126, "The voter is already part of the set of voters."],
  [127, "The voter is not part of the set of voters."],
  [128, "The regular expression is not valid."],
  [129, "Client metadata is stale, client should rebootstrap to obtain new metadata."],
  [130, "The supplied topology is invalid."],
  [131, "The supplied topology epoch is invalid."],
  [132, "The supplied topology epoch is outdated."],
  [133, "The limit of share sessions has been reached."],
]);

/** code → constant name (`-185` → `"ERR__TIMED_OUT"`). */
export const ERROR_NAMES: Readonly<Record<number, string>> = /* @__PURE__ */ (() => {
  const out: Record<number, string> = {};
  for (const [name, code] of Object.entries(ERROR_CODES)) {
    // The v2.15.0 table has no duplicate values, but keep "first wins" so that
    // if librdkafka later adds aliases, the earlier-declared name still wins.
    if (out[code] === undefined) out[code] = name;
  }
  return Object.freeze(out);
})();

/** Boundary of librdkafka's internal error range: code <= -100 is a "local" error. */
const LOCAL_ERR_MAX = ERROR_CODES.ERR__END;

/** Is this code a client-internal error (not one returned by the broker)? */
export function isLocalError(code: number): boolean {
  return code <= LOCAL_ERR_MAX;
}

/** Constant name of an `rd_kafka_resp_err_t`, or `undefined` when unknown. */
export function errorName(code: number): string | undefined {
  return ERROR_NAMES[code];
}

/** Human-readable description of an `rd_kafka_resp_err_t`. */
export function errorDescription(code: number): string {
  return ERROR_DESCRIPTIONS.get(code) ?? ERROR_NAMES[code] ?? `Unknown error ${code}`;
}

/* ========================================================================== */
/* LibrdKafkaError                                                             */
/* ========================================================================== */

/**
 * - `"kafka"`  — error returned by the broker (code >= -100)
 * - `"local"`  — librdkafka-internal error (code <= -100), matching upstream
 * - `"shim"`   — C shim layer error (`BRK_ERR_*`), NOT a librdkafka code
 */
export type ErrorOrigin = "local" | "kafka" | "shim";

export interface LibrdKafkaErrorInit {
  code?: number;
  origin?: ErrorOrigin;
  isFatal?: boolean;
  isRetriable?: boolean;
  isTxnRequiresAbort?: boolean;
  /** Extra debugging info (name of the FFI function being called…). */
  context?: string;
}

/**
 * Mirrors confluent-kafka-javascript's `LibrdKafkaError`:
 * `{ message, code, errno, origin, isFatal, isRetriable, isTxnRequiresAbort }`.
 */
export class LibrdKafkaError extends Error {
  override readonly name: string = "LibrdKafkaError";
  readonly code: number;
  /** Alias of `code` (upstream exposes both). */
  readonly errno: number;
  readonly origin: ErrorOrigin;
  readonly isFatal: boolean;
  readonly isRetriable: boolean;
  readonly isTxnRequiresAbort: boolean;
  readonly context: string | undefined;

  constructor(message: string, init: LibrdKafkaErrorInit = {}) {
    super(message);
    this.code = init.code ?? ERROR_CODES.ERR_UNKNOWN;
    this.errno = this.code;
    this.origin = init.origin ?? (isLocalError(this.code) ? "local" : "kafka");
    this.isFatal = init.isFatal ?? this.code === ERROR_CODES.ERR__FATAL;
    this.isRetriable = init.isRetriable ?? false;
    this.isTxnRequiresAbort = init.isTxnRequiresAbort ?? false;
    this.context = init.context;
  }

  /** Builds from a plain `rd_kafka_resp_err_t`. */
  static fromKafkaCode(
    code: number,
    message?: string,
    init: Omit<LibrdKafkaErrorInit, "code"> = {},
  ): LibrdKafkaError {
    return new LibrdKafkaError(message || errorDescription(code), { ...init, code });
  }

  /** Builds from a shim-layer error code (`BRK_ERR_*`, range -99..-1). */
  static fromShimCode(brkCode: number, message?: string, context?: string): LibrdKafkaError {
    const label = BRK_ERR_NAMES[brkCode] ?? `BRK_ERR(${brkCode})`;
    return new LibrdKafkaError(message || `bun-rdkafka native shim: ${label}`, {
      code: brkCode,
      origin: "shim",
      ...(context === undefined ? {} : { context }),
    });
  }

  /**
   * Decodes a `brk_*` function's negative return value into an error.
   * Returns `undefined` when `ret >= 0` (success).
   */
  static fromReturn(
    ret: number,
    context?: string,
    message?: string,
  ): LibrdKafkaError | undefined {
    if (ret >= 0) return undefined;
    if (isKafkaErr(ret)) {
      const code = kafkaErrOf(ret);
      return new LibrdKafkaError(message || errorDescription(code), {
        code,
        ...(context === undefined ? {} : { context }),
      });
    }
    if (isShimErr(ret)) return LibrdKafkaError.fromShimCode(ret, message, context);
    return new LibrdKafkaError(
      message || `bun-rdkafka: invalid return value from native: ${ret}`,
      {
        code: ret,
        origin: "shim",
        ...(context === undefined ? {} : { context }),
      },
    );
  }

  /**
   * Builds an error from `ret` + the errstr written by the shim.
   *
   * The shim appends `[txn-requires-abort]` / `[retriable]` markers to the
   * errstr for the transaction group (librdkafka returns an `rd_kafka_error_t`
   * with these two flags, which the POD ABI cannot carry) — see
   * `native/src/shim_producer.c`.
   * TODO(M4): drop this parsing if the shim switches to flag bits in ret.
   */
  static fromErrstr(ret: number, context: string, errstr: string): LibrdKafkaError {
    const parsed = parseErrstrFlags(errstr);
    const base = LibrdKafkaError.fromReturn(
      ret,
      context,
      parsed.message ? `${context}: ${parsed.message}` : undefined,
    );
    if (!base) {
      throw new TypeError(`fromErrstr() called with a non-error ret: ${ret}`);
    }
    return new LibrdKafkaError(base.message, {
      code: base.code,
      origin: base.origin,
      isFatal: base.isFatal,
      isRetriable: parsed.isRetriable,
      isTxnRequiresAbort: parsed.isTxnRequiresAbort,
      context,
    });
  }

  toJSON(): Record<string, unknown> {
    return {
      name: this.name,
      message: this.message,
      code: this.code,
      errno: this.errno,
      origin: this.origin,
      isFatal: this.isFatal,
      isRetriable: this.isRetriable,
      isTxnRequiresAbort: this.isTxnRequiresAbort,
    };
  }
}

/* ========================================================================== */
/* Transaction flags embedded in the errstr (side contract with shim_producer.c) */
/* ========================================================================== */

/** Marker the shim appends to the errstr on `rd_kafka_error_txn_requires_abort()`. */
export const ERRSTR_FLAG_TXN_REQUIRES_ABORT = "[txn-requires-abort]";
/** Marker the shim appends to the errstr on `rd_kafka_error_is_retriable()`. */
export const ERRSTR_FLAG_RETRIABLE = "[retriable]";

export interface ParsedErrstr {
  /** errstr with markers stripped and trimmed. */
  message: string;
  isRetriable: boolean;
  isTxnRequiresAbort: boolean;
}

/** Splits the `[retriable]` / `[txn-requires-abort]` flags out of the shim's errstr. */
export function parseErrstrFlags(errstr: string): ParsedErrstr {
  let message = errstr;
  const isTxnRequiresAbort = message.includes(ERRSTR_FLAG_TXN_REQUIRES_ABORT);
  const isRetriable = message.includes(ERRSTR_FLAG_RETRIABLE);
  if (isTxnRequiresAbort) message = message.split(ERRSTR_FLAG_TXN_REQUIRES_ABORT).join("");
  if (isRetriable) message = message.split(ERRSTR_FLAG_RETRIABLE).join("");
  return { message: message.trim(), isRetriable, isTxnRequiresAbort };
}

/** Throws if `ret < 0`, otherwise returns `ret`. */
export function throwOnError(ret: number, context?: string, message?: string): number {
  const err = LibrdKafkaError.fromReturn(ret, context, message);
  if (err) throw err;
  return ret;
}

/** Same as {@link LibrdKafkaError.fromReturn} — a short name for the core layer. */
export function decodeReturn(
  ret: number,
  context?: string,
  message?: string,
): LibrdKafkaError | undefined {
  return LibrdKafkaError.fromReturn(ret, context, message);
}
